version: "3.4"

services:
  db:
    image: postgres
    container_name: db_container
    restart: always
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  flask-app:
    build:
      context: .
      dockerfile: python/Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ./python/src:/app
      - ./python/data:/app/data
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: flask_app

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning