version: "3.4"

services:
  db:
    image: postgres
    container_name: db_container
    restart: always
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"